model_parameters:
  onnx_model: "best.onnx"
  output_model_file_prefix: "yolov8_horizon"
  march: "bernoulli2"
  layer_out_dump: False
  working_dir: "model_outputs"

input_parameters:
  input_name: "images"
  # input_shape: '1x3x416x416'
  input_shape: "1x3x640x640"
  input_batch: 1
  # [待配置参数]，见思维导图"输入信息参数组/原始模型参数"部分
  input_type_train: "rgb"
  input_layout_train: "NCHW"

  # [待配置参数]，见思维导图"输入信息参数组/转换后模型参数"部分
  # ['nv12', 'yuv444', 'rgb', 'bgr', 'gray', 'featuremap']

  # input_type_rt: "nv12"
  # 这里由于我不想输入 nv12 数据，我觉得直接输入 bgr 前处理只需要 resize 就好了简单
  input_type_rt: 'nv12'
  # [待配置参数]，见思维导图"输入信息参数组/输入数据预处理"部分
  norm_type: "data_scale"
  scale_value: 0.003921568627451

  # 默认参数，暂不需要理解
  input_layout_rt: "NHWC"

# 校准参数组，全部默认
calibration_parameters:
  # cal_data_dir: '/open_explorer/horizon/calib_data/calib_416_f32'
  cal_data_dir: "./calib_640_f32"
  cal_data_type: "float32"
  calibration_type: "default" # default kl
  # max_percentile: 0.99999 # 0.99999、0.99995、0.9999、0.9995、0.999
  # per_channel: True

# 编译参数组，全部默认
compiler_parameters:
  compile_mode: "latency"
  optimize_level: "O3"
  debug: False # 别看官网写的可选，实际上不写这个出bug
  core_num: 2